server:
  port: 8080
spring:
  application:
    name: "accounts"
  datasource:
    url: jdbc:mysql://localhost:3306/accountsdb
    username: root
    password: alok
  sql:
    init:
      mode: always
  jpa:
    show-sql: true
  config:
    import: "optional:configserver:http://localhost:8071/"
#  rabbitmq:
#    host: "localhost"
#    username: "guest"
#    password: "guest"
#    port: 5672

management:
  endpoints:
    web:
      exposure:
        include: "*"

